apiVersion: apps/v1
kind: Deployment
metadata:
  name: nest-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nest-app
  template:
    metadata:
      labels:
        app: nest-app
    spec:
      containers:
      - name: nest-app
        image: juancho637/nestjs-clean:latest
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: nest-app-config
