apiVersion: apps/v1
kind: Deployment
metadata:
  name: recognition-deployment
  labels:
    app: recognition
spec:
  replicas: 2
  selector:
    matchLabels:
      app: recognition
  template:
    metadata:
      labels:
        app: recognition
    spec:
      containers:
      - name: recognition
        image: juancho637/recognition:v2
        ports:
        - containerPort: 5000
